# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  name: qbittorrent-nox
  version: "5.1.0"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  url: https://github.com/qbittorrent/qBittorrent/archive/refs/tags/release-${{ version }}.tar.gz
  sha256: ac54cd8b3c6035cfcd684be5afd0eccc8c5fbbc3008a9b6f9ba42f6ef91105af

build:
  number: 0
  script:
    content:
      - |
        cmake ${CMAKE_ARGS} \
          -G "Ninja" \
          -D TESTING=OFF \
          -D GUI=OFF \
          .

      - ninja install

requirements:
  build:
    - "${{ compiler('c') }}"
    - "${{ compiler('cxx') }}"
    - ninja
    - cmake

  host:
    - boost>=1.84.0
    - openssl>=3.0.0
    - qt6-main>=6.7,<6.8.0a0
    - zlib>=1.2.11
    - libtorrent-static

tests:
  - script:
      - qbittorrent-nox --help
