# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  name: qbittorrent-nox
  version: "5.0.2"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  url: https://github.com/qbittorrent/qBittorrent/archive/refs/tags/release-${{ version }}.tar.gz
  sha256: ba46f7ac0c530ab6ba81fdce6f4488393cd67dd1a9d823660e26081773569274

build:
  number: 0
  script:
    content:
      - |
        cmake ${CMAKE_ARGS} -G "Ninja" \
          -D TESTING=OFF \
          -D GUI=OFF \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          .

      - ninja install

requirements:
  build:
    - "${{ compiler('c') }}"
    - boost>=1.84.0
    - cmake
    - openssl
    - qt6-main==6.6.3
    - "${{ compiler('cxx') }}"
    - zlib
    - libtorrent-static

  host:
    - openssl
    - zlib
    - libtorrent-static

  run:
    - ${{ pin_subpackage("openssl", exact=True) }}
    - ${{ pin_subpackage("qt6-main", exact=True) }}
    - ${{ pin_subpackage("zlib", exact=True) }}

tests:
  - script:
      - qbittorrent-nox --help

about:
  license: MIT
  summary: An extremely fast Python linter, written in Rust.
  # The remaining entries in this section are optional, but recommended.
  description: |
    An extremely fast Python linter, written in Rust. Ruff can be used to
    replace Flake8 (plus a variety of plugins), isort, pydocstyle, yesqa, and
    even a subset of pyupgrade and autoflake all while executing tens or
    hundreds of times faster than any individual tool.
  homepage: https://github.com/astral-sh/ruff
  repository: https://github.com/astral-sh/ruff
