# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  name: qbittorrent-nox
  version: "5.0.3"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  git: https://github.com/qbittorrent/qBittorrent
  tag: 'release-${{ version }}'

build:
  number: 0
  script:
    content:
      - |
        cmake ${CMAKE_ARGS} \
          -G "Ninja" \
          -D TESTING=OFF \
          -D GUI=OFF \
          .

      - ninja install

requirements:
  build:
    - "${{ compiler('c') }}"
    - "${{ compiler('cxx') }}"
    - ninja
    - cmake

  host:
    - boost>=1.84.0
    - openssl>=3.0.0
    - qt6-main>=6.8,<6.9.0a0
    - zlib>=1.2.11
    - libtorrent-static

tests:
  - script:
      - qbittorrent-nox --help
