# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  name: libtorrent-static
  version: "2.0.11"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  url: "https://github.com/arvidn/libtorrent/releases/download/v${{ version }}/libtorrent-rasterbar-${{ version }}.tar.gz"
  sha256: f0db58580f4f29ade6cc40fa4ba80e2c9a70c90265cd77332d3cdec37ecf1e6d

build:
  number: 0
  script:
    content:
      - |
        cmake ${CMAKE_ARGS} \
          -G "Ninja" \
          -D BUILD_SHARED_LIBS=OFF \
          .

      - ninja install

requirements:
  build:
    - "${{ compiler('c') }}"
    - cmake
    - ninja
    - "${{ compiler('cxx') }}"

  host:
    - boost>=1.84.0
    - openssl>=3.0.0

  run:
    - ${{ pin_compatible("boost", lower_bound="x.x", upper_bound="x.x") }}
    - ${{ pin_compatible("openssl", lower_bound="x.x", upper_bound="x") }}
