# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  name: libtorrent-static
  version: "2.0.11"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  url: "https://github.com/arvidn/libtorrent/releases/download/v${{ version }}/libtorrent-rasterbar-${{ version }}.tar.gz"
  sha256: f0db58580f4f29ade6cc40fa4ba80e2c9a70c90265cd77332d3cdec37ecf1e6d

build:
  number: 0
  script:
    env:
      ACTIONS_CACHE_SERVICE_V2: '${{ env.get("ACTIONS_CACHE_SERVICE_V2", default="") }}'
      ACTIONS_RESULTS_URL: '${{ env.get("ACTIONS_RESULTS_URL", default="") }}'
      ACTIONS_RUNTIME_TOKEN: '${{ env.get("ACTIONS_RUNTIME_TOKEN", default="") }}'
      SCCACHE_GHA_ENABLED: '${{ env.get("SCCACHE_GHA_ENABLED", default="") }}'
    content:
      - sccache --show-stats

      - |
        cmake ${CMAKE_ARGS} -G "Ninja" \
          -D BUILD_TESTING=OFF \
          -D BUILD_SHARED_LIBS=OFF \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          -DCMAKE_C_COMPILER_LAUNCHER=sccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
          .

      - ninja install
      - sccache --show-stats

requirements:
  build:
    - "${{ compiler('c') }}"
    - boost>=1.84.0
    - cmake
    - sccache
    - openssl
    - "${{ compiler('cxx') }}"
  host:
    - openssl
