# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  name: libtorrent-static
  version: "1.2.20"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  url: "https://github.com/arvidn/libtorrent/releases/download/v${{ version }}/libtorrent-rasterbar-${{ version }}.tar.gz"
  sha256: ccbf8e8c21dc81635de95166b498922b4725f9725a23b2cfe2a6b2fead6fb9fc

build:
  number: 2
  script:
    content:
      - |
        cmake ${CMAKE_ARGS} \
          -G "Ninja" \
          -D BUILD_SHARED_LIBS=OFF \
          .

      - ninja install

requirements:
  build:
    - "${{ compiler('c') }}"
    - "${{ compiler('cxx') }}"
    - cmake
    - ninja
    - compilers

  host:
    - boost>=1.84.0
    - openssl>=3.0.0
