name: build conda packages

on:
  workflow_call:

jobs:
  build-x64:
    name: Build conda
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - "ubuntu-24.04"
          # - "ubuntu-24.04-arm"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install the latest Wasmer version
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: prefix-dev/rattler-build
          tag: "v0.41.0"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - run: |
          rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --output-dir=./output \
            --verbose \
            --recipe-dir=packages/libtorrent-static
        shell: bash

      - run: |
          rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --output-dir=./output \
            --verbose \
            --recipe-dir=recipe
        shell: bash

      - run: ls ./output/

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "conda-${{ matrix.os }}"
          path: ./output/*/*.conda
