name: build conda packages

on:
  workflow_call:

jobs:
  build-x64:
    name: Build conda
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - "ubuntu-24.04"
          - "ubuntu-24.04-arm"
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest Wasmer version
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: prefix-dev/rattler-build
          tag: "v0.41.0"

      - run: |
          rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --skip-existing=all \
            --output-dir=./output \
            --channel=conda-forge \
            --channel=https://repo.prefix.dev/bit-torrent \
            --verbose \
            --recipe-dir=packages/libtorrent
        shell: bash

      - run: |
          rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --skip-existing=all \
            --output-dir=./output \
            --channel=conda-forge \
            --channel=https://repo.prefix.dev/bit-torrent \
            --verbose \
            --recipe-dir=packages/qbittorrent
        shell: bash

      - run: ls ./output/

      - uses: actions/upload-artifact@v4
        with:
          name: "conda-${{ runner.os }}-${{ runner.arch }}"
          path: ./output/*/*.conda
