name: build conda packages

on:
  workflow_call:

jobs:
  build:
    name: Build conda
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: prefix-dev/setup-pixi@19eac09b398e3d0c747adc7921926a6d802df4da # v0.8.8

      - run: |
          pixi run rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --output-dir=./output \
            --verbose \
            --recipe-dir=recipe
        shell: bash

      - run: ls ./output/

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "conda-noarch"
          path: ./output/noarch/*.conda
          if-no-files-found: ignore
