name: build conda packages

on:
  workflow_call:

jobs:
  build-lt:
    name: Build libtorrent
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        version:
          - "1"
          - "2"
        os:
          - "ubuntu-24.04"
          - "ubuntu-24.04-arm"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: prefix-dev/rattler-build
          tag: "v0.41.0"

      - run: |
          rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --skip-existing=all \
            --output-dir=./output \
            --channel=conda-forge \
            --channel=https://repo.prefix.dev/bit-torrent \
            --verbose \
            --recipe-dir=packages/libtorrent/v${{ matrix.version }}
        shell: bash

      - run: rm ./output/bld/ ./output/src_cache/ -rf

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "conda-lt-${{ runner.os }}-${{ runner.arch }}-${{ matrix.version }}"
          path: ./output/*/libtorrent-*.conda

  build-repo:
    name: build a repo
    runs-on: "ubuntu-24.04"
    needs:
      - build-lt
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: conda-lt-*
          path: output
          merge-multiple: true

      - uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: prefix-dev/pixi
          tag: "v0.46.0"

      - run: |
          pixi global install conda --with conda-index
          conda index --verbose --threads=4 output

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "repo"
          path: ./output/

  build-qb:
    name: Build qbittorrent
    needs:
      - build-repo
      - build-lt
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        version:
          - "5.0"
          - "5.1"
        os:
          - "ubuntu-24.04"
          - "ubuntu-24.04-arm"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: prefix-dev/rattler-build
          tag: "v0.41.0"

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: "repo"
          path: ./output/

      - run: |
          rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --skip-existing=all \
            --output-dir=./output \
            --channel=conda-forge \
            --channel=https://repo.prefix.dev/bit-torrent \
            --verbose \
            --recipe-dir=packages/qbittorrent/${{ matrix.version }}
        shell: bash

      - run: ls ./output/

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "conda-qb-${{ runner.os }}-${{ runner.arch }}-${{ strategy.job-index }}"
          path: ./output/*/qbittorrnet-*.conda
