name: build conda packages

on:
  workflow_call:

jobs:
  build:
    name: Build conda
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: prefix-dev/setup-pixi@dbaed5efa0bd33d6bd6d162bec8a06d8fc43c807 # v0.8.5

      - run: |
          pixi run rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --skip-existing=all \
            --channel=conda-forge \
            --output-dir=./output \
            --verbose \
            --variant-config=variants.yaml \
            --recipe-dir=packages
        shell: bash

      - run: ls ./output/

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "conda-noarch"
          path: ./output/noarch/*.conda
          if-no-files-found: ignore
